-- API Count
SELECT COUNT(*) FROM AM_API;
-- App Count
SELECT COUNT(*) FROM AM_APPLICATION;
-- Total active token Count
SELECT COUNT (*) FROM IDN_OAUTH2_ACCESS_TOKEN WHERE TOKEN_STATE='ACTIVE';
-- Total SP Count
SELECT COUNT (*) FROM IDN_OAUTH_CONSUMER_APPS;
SELECT COUNT (*) FROM SP_APP;
-- Check avaibiliy of Multiple Key Managers
SELECT DISTINCT(TYPE) FROM AM_KEY_MANAGER;
-- Token Type of currently consuming
SELECT DISTINCT(TOKEN_TYPE) FROM AM_APPLICATION;
-- Grnat type usage
SELECT DISTINCT(GRANT_TYPE) FROM IDN_OAUTH2_ACCESS_TOKEN;
-- AUTH Code grant type usage
SELECT COUNT(*) FROM IDN_OAUTH2_AUTHORIZATION_CODE;
-- Never expired access token avaibiliy
SELECT COUNT(*) FROM IDN_OAUTH2_ACCESS_TOKEN WHERE VALIDITY_PERIOD LIKE '%-%';
